### ISSUE TITLE
Additions to the backend scoring system

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#149]
- [x] **`P3`** Add the tie-breakers is all scoreboards (ref. https://github.com/pil0u/lewagon-aoc/issues/66#issuecomment-1193216875)

## Completions
For a given completion <day, challenge, user>
  - [ ] **`P1`** Add the `score` - the insanity score if the user has enrolled insanity, the casual otherwise
  - [ ] **`P1`** Add the `rank` - based on the time to solve vs others

## Squads
- [x] **`P1`** Add the `daily_score` attribute (default: `0`) - the score of the current puzzle since 06:00am CET
- [ ] **`P2`** Add the `previous_rank` attribute - the rank of the entity frozen at 05:59am CET
- [ ] **`P3`** Add the `silver_stars` and `golden_stars` attributes (default: `0`) - currently computed in `SquadsController`
- ~**`P3`** Add the `display_rank` attribute (boolean) - currently computed in `ScoresController`~ (intended behavior)

## Cities
- ~**`P1`** Add the `daily_score` attribute (default: `0`) - the score of the current puzzle since 06:00am CET~ (N/A to current design)
- [x] **`P1`** Add the `daily_contributors_part_1` and `daily_contributors_part_2` attributes (default: `0`)
- [ ] **`P2`** Add the `previous_rank` attribute - the rank of the entity frozen at 05:59am CET
- [ ] **`P3`** Add the `silver_stars` and `golden_stars` attributes (default: `0`) - currently computed in `CitiesController`
- ~**`P3`** Add the `display_rank` attribute (boolean) - currently computed in `ScoresController`~ (intended behavior)

## Solo
- [x] **`P1`** Add the `daily_score` attribute (default: `0`) - the score of the current puzzle since 06:00am CET
- [ ] **`P2`** Add the `previous_rank` attribute - the rank of the entity frozen at 05:59am CET
- ~**`P3`** Add the `display_rank` attribute (boolean) - currently computed in `ScoresController`~ (intended behavior)

## Insanity
- [x] **`P1`** Add the `daily_score` attribute - the score of the current puzzle since 06:00am CET
- [ ] **`P2`** Add the `previous_rank` attribute - the rank of the entity frozen at 05:59am CET
- ~**`P3`** Add the `display_rank` attribute (boolean) - currently computed in `ScoresController`~ (intended behavior)

**Comment by Aquaj** [comment]
Bringing Tie-Breakers message from original conversation here for easier reference:

> ## Tie-breakers
> 
> ### Casual solo
> 
> - Score
> - Number of challenges solved in less than 24 hours
> - Number of challenges solved in less than 48 hours
> 
> ### Squads
> 
> - Score
> - Total number of challenges solved in less than 24 hours by squad members
> - Total number of challenges solved in less than 48 hours by squad members
> 
> ### Cities
> 
> - Score
> - Total number of challenges solved in less than 24 hours by their top contributors (top 5% or top 10)
> - Total number of challenges solved in less than 48 hours by their top contributors (top 5% or top 10)
> 
> ### Ladder of Insanity
> 
> - Score
> - Total time to solve challenges

**Comment by Aquaj** [comment]
Ça dépend. Techniquement #220 n'implémente que `P3 Add the tie-breakers is all scoreboards`. Les autres non-cochées sont toujours à faire.
Peut-être simplement à fermer pour staleness et réouvrir avec un dépoussiérage et une repriorisation. (voir à splitter en plusieurs issues ?)

**Comment by wJoenn** [comment]
#220 est merged, je vous laisse voir ce que vous voulez faire de cette issue
