### ISSUE TITLE
Don't display the date of messages on mobile

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#160]
In The Wall, the current HTML layout breaks the single line of the date + the username. Alternatives:
- shorten the date format on mobile
- don't display it at all

**Comment by wJoenn** [comment]
I tried a couple of ideas including changing the size of the text it in sm breakpoint but that would make it very difficult to read. Increasing the width of the messages box_component to 100% but depending on username's length that wasn't enough and I believe that goes against the initial design of having user messages on the right and other user's on the left.
Changing the display of the data with #strftime which could make the trick but :
In the end this is hoverable feature and they don't play very well on mobile as you never hover in this format. The information is available on touch and persist but I don't believe that the feature is needed so the easiest and best solution imo would be to set the created_at span tag as hidden then set as inline when breakpoint is md or above.
span.hidden.md:inline
