### ISSUE TITLE
Le solo scoreboard est très long à charger côté front

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#163]
The Solo scoreboard is very slow to _render_. Loading only the 50-100 first rows with the page and let the rest lazy load.

**Comment by Aquaj** [comment]
Peut-être #220 aidera aussi, vu qu'on gardera des infos supplémentaires en cache au lieu de les recompute à la volée dans le présenter. On a aussi du cache HTML à mettre en place pour finir d'enterrer les soucis de perf, je pense — vu qu'on rerender bcp les mêmes trucs.

**Comment by pil0u** [comment]
The remaining large score boards will be lazy loaded (in a future issue)
