### ISSUE TITLE
Assigner automatiquement un utilisateur à son campus et son batch

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#177]
- [ ] Store the file of the mapping and load it
- [ ] Make sure to map each batch number with the proper city name (see `seed.rb`)
- [ ] Upon user creation, map the proper city from its batch number
- [ ] Lock the batch number and the city name
- [ ] Update existing user in the production database with their proper batch number and city (first, evaluate the impact)

**Comment by wJoenn** [comment]
On it
