### ISSUE TITLE
Permettre aux utilisateurs de changer leurs paramètres pendant la phase de setup

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#201]
Voici la page actuellement :
![Screenshot 2023-10-06 at 09 54 37](https://github.com/pil0u/lewagon-aoc/assets/8350914/bee12070-5c17-4656-92ba-298d335fa5db)

L'idée serait d'ajouter les éléments de paramètres utilisateurs tout en bas, "In the mean time, you can play with your settings" quelque chose de ce genre.

![Screenshot 2023-10-06 at 09 58 06](https://github.com/pil0u/lewagon-aoc/assets/8350914/dd5ea8df-c7b3-4be2-a541-adf408df5434)

Paramètres changeables : 
- `username`
- `batch #`
- `campus`
- ~~`ladder of insanity`~~ (à supprimer dans #244)

**Comment by wJoenn** [comment]
le batch number et la ville vont etre disabled par https://github.com/pil0u/lewagon-aoc/pull/212
l'id AoC est deja disabled
Tu veux enlever le toggle pour la ladder of insanity
Au final tout ce qui reste c'est le pseudo.

Est ce qu'on enleverais pas la page de settings carrement avec juste une option pour choisir son pseudo lors de l'inscription ?
Par "enlever" je penses plutot a la cacher pour 90% des Users puisque le reste aura quand meme besoin d'aller ajouter un batch a son compte si il n'en a pas deja
