### ISSUE TITLE
Ajouter un bouton "Sign in" sur la page 404

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#211]
Parfois, les utilisateurs chargent certains liens (depuis Slack) mais ne sont plus connectés à l'app sur le navigateur. Ils tombent alors sur la page 404.

Je vois 2 options : 

1. (idéale) Modifier la logique des routes, pour que l'utilisateur soit redirigé vers le lien d'authentification OAuth, puis vers la page qu'il a demandé automatiquement
2. (rapide) Ajouter un message sur la page 404:

```html
<body>
  <h1>404 Not Found</h1>
  <p>Hint: you might not be signed in</p>
  <a href="/">Go back</a>
</body>
```

**Comment by wJoenn** [comment]
Je penses que ca serait quand meme mieux de faire l'option 1.
C'est mieux niveau UX je trouve 🤔 
Suffirait de descope les routes et de whitelist `authenticate_user` sur les routes qu'on veut changer et normalement on ajoute juste ce scope la dans les routes pour que devise redirige vers la homepage
```ruby
devise_scope :user do
  root to: "devise/sessions#new"
end
```
