### ISSUE TITLE
Renommer le modèle `City` en `Campus`

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#214]
La notion de "ville" est un peu biaisée du fait qu'il existe les campus `Online` (1322 Alumni), `For Business` (190 Alumni) ou encore `Emil` (175 Alumni)

Pour tous ces Alumni, la terminologie porte à confusion.

Au moins changer dans ce qui est affiché aux utilisateurs, idéalement dans le code également (mais plus pénible et beaucoup moins nécessaire)

**Comment by wJoenn** [comment]
I could do this as part of #212 if you want
