### ISSUE TITLE
Staging ? Déploiement ? État pour 2023

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#236]
TL;DR sans staging, tout va se passer directement sur https://aoc.lewagon.community/ une fois push sur `main`.

---

J'ai tenté de déployer un staging sur Fly, c'était pénible et je trouve leur service trop instable.

@ssaunier si tu vois ce message, je t'ai envoyé [un MP sur Slack](https://lewagon-alumni.slack.com/archives/DRXLQV0KC/p1687531162674519) pour savoir si c'était possible d'avoir un vrai staging (`lewagon-aoc-staging` avec une base de données de la même taille) + un pipeline sur Heroku, ça nous aiderait pour le rush avant décembre.

En attendant, ma suggestion :
- travailler directement sur `main` - avec PR systématique
- travailler directement en production - déploiement automatique après un push sur `main` déjà en place

C'est pas idéal si des utilisateurs passent sur le site régulièrement mais tant pis.
J'ai effectué un backup de la base de données, vous pouvez tout casser.

Demandez-moi si vous avez besoin de réaliser des actions de déploiement en particulier sur l'app de production.
@Aquaj je t'envoie les identifiants de la base de données de prod en privé 👍 

---

**Comment by ssaunier** [comment]
@pil0u c'est quoi ton email Heroku? Je peux créer une app + t'inviter. Tu peux me shooter ton email Heroku à mon email (`seb@...`).

**Comment by wJoenn** [comment]
J'ai l'habitude d'avoir `main` comme staging auto et un deploiement en prod auto on merge sur `prod` avec merge sur prod manuel perso. Je crois que ca se rapproche plus de ta deuxieme proposition ?
Ce qui est sympa c'est un staging par branch mais je sais pas si Heroku propose ca

**Comment by ssaunier** [comment]
> Avec un pipeline Heroku il y a les Review Apps par branche, mais elles ne sont pas activées pour le moment.

il faut payer pour chaque review app non ? J’aimerai que vous vous limitiez à 2 apps (prod + staging) mappées à 2 branches en auto release par ex. Merci !

**Comment by Aquaj** [comment]
Le staging est largement suffisant.

Pour les conventions, je bosse avec `main == prod` au quotidien (+ branche `staging`) en mode Trunk-Based Development + Continuous Deployment, mais aucun souci pour bosser avec `release == prod` + `main == staging` si c'est le formalisme qui vous va le mieux.

**Comment by Aquaj** [comment]
Absolument pas 😄 On a besoin de PRs pour permettre la review, surtout quand on voit des PRs aussi conséquentes que #212 ou #220. On est pas assez pour faire du pair à chaque dev.
Pour le coup mon quotidien c'est le "Scaled Trunk-Based Development" — il est particulièrement applicable vu que je suis dans une boîte et équipe plus conséquente en taille, mais en pratique je trouve le flot applicable à plus petite échelle aussi.

Peu importe en vrai. On garde le système qu'on a l'heure actuelle, avec juste l'ajout du déploiement auto release->prod et du déploiement auto main->staging, ça marchera très bien.
On fait nos devs via PRs, c'est mergé quand ça semble ok, ça s'empile dans le staging (`main`) et quand on est content de notre état en staging on en fait une release via merge dans `release`.
