### ISSUE TITLE
[Meta] Mise à jour du système de scores

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#241]
Selon le questionnaire final, l'ordre d'importance des types de classements est le suivant : 
```
Campus > Individuels > Squads
```

# Scores de campus

- [x] #242
```
5% * N Alumni 2023 + 3% * N Alumni 2022 + 1% * N Alumni 2021 et avant
```
- [x] #243 

# Scores individuels

- [x] #244

# Scores de squads

Les squads ont été introduites en 2022 et bien appréciées.

Quelques idées ont été émises : 
* les rendre aléatoires
* plutôt que d'avoir plein de squads de 4 personnes, avoir 3-4 squads avec plein de personnes

À discuter.

**Update : pas de changement pour les Squads, on reste comme ça** 👍

**Comment by Aquaj** [comment]
> Pour le côté aléatoire, l'avantage que je vois c'est de générer des rencontres qui n'auraient pas pu avoir lieu autrement, et tant pis si ça tombe à l'eau

Complètement d'accord, et je suis partisan qu'on garde cette volonté notée qq part par contre parce que je la partage aussi, je pense juste qu'on peut trouver une autre feature pour répondre à ça. 
Peut-être un "buddy du jour" aléatoire et vous gagnez tous les deux un bonus de points si vous finissez tous les deux l'exo en <24h ? Peut-être en pseudo-aléatoire pour encourager certains types de rencontre ?
Ça ferait un truc un peu similaire aux Friends Quest de Duolingo, si ça parle.

> ça me va de garder le système de Squads tel quel, je préfère largement mettre un bout d'effort ailleurs.

Je préfère largement investir dans la connexion à Slack par exemple yes. Même si c'est pas _hyper coûteux_ de faire du random. Donc si on part sur ça ça pourra s'implémenter "à la va-vite" avant le démarrage.

> Idée : lancer un sondage dans #aoc pour ajuster la taille des Squads (proposer 3, 4 (actuel), 5, ou 6), vous validez ou on change rien ?

J'aime bien notre taille de 4 mais demander fait pas de mal.

**Comment by Aquaj** [comment]
Je l'ai connu t'en fais pas 😉 Je trouve le parallèle assez élégant en terme de design vu notre cible d'users.
