### ISSUE TITLE
Modifier la formule des `top contributors` pour les campus

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#242]
Afin de ne pas trop pénaliser les campus qui ont des Alumni depuis 2014 dont la plupart sont inactifs, l'idée est de remplacer la formule : 
```
3% * total Alumni du campus
```
par une pondération plus modérée : 
```
5% * Alumni de 2023 + 3% * Alumni de 2022 + 1% * Alumni de 2021 et avant
```
et toujours conserver un minimum à `10` quoi qu'il arrive.

**Comment by julesvanrie** [comment]
Complètement d'accord avec le principe. 

Faut juste réfléchir sur l'impact des bootcamp Data Analytics avec des étudiants profil "no / low code". Ceci pourrait pénaliser les petits campus qui se sont focalisé sur DA en 2023 au lieu de DS.

**Comment by Aquaj** [comment]
On a même quelques exemples de cadors qui fracassent les temps des devs classiques avec une approche data (je pense à Pierre Vermeulen par exemple).
