### ISSUE TITLE
Supprimer l'opt-in du Ladder of Insanity : tout le monde dedans

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#244]
Le côté opt-in du Ladder of Insanity était trop compliqué à comprendre pour la plupart des utilisateurs.
Quite à garder les deux classements individuels, autant que tout le monde soit dedans par défaut.

- [ ] Supprimer l'option dans l'UI
- [ ] Supprimer le booléen dans le modèle utilisateur
- [ ] Supprimer le lien avec le Lock time
- [ ] ...

**Comment by wJoenn** [comment]
Si le probleme c'est que les gens ont trop de mal a s'y inscrire.
Pourquoi ne pas simplement modifier le default pour que les gens soient inscrit de base et doivent se desinscrire si ils ne veulent pas etre dedans ?

Je suis pas sur de comprendre quel est le probleme de cette issue tbh.
Je trouvais le fonctionnement des deux leaderboard parfaitement fonctionnel l'an dernier (perso je regardais que le leaderboard de l'insanity)
