### ISSUE TITLE
Désagrément : `cache_key` est un attribut réservé d'ActiveRecord

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#248]
La méthode d'instance `cache_key` est [utilisée par ActiveRecord](https://apidock.com/rails/ActiveRecord/Base/cache_key) et nous la réécrivons pour tout autre chose, dans de nombreux modèles.

Ça pourrait être plus clean d'avoir un nom différent.

**Comment by Aquaj** [comment]
Je croyais que j'étais passé à `cache_fingerprint` pour éviter exactement ça ? Faut que je me replonge dans le code mais j'ai peut-être pas été assez exhaustif dans mon approche.
