### ISSUE TITLE
Ajout d'un langage de programmation préféré dans ses paramètres

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#257]
* À choisir parmi la liste des langages qu'on supporte via le code sharing
* Possibilité de le modifier au moment du setup/inscription
* Devient la valeur par défaut quand on veut partager un snippet

**Comment by wJoenn** [comment]
Est ce qu'il y a une raison pour laquelle on n'accepte pas d'autre languages ?
Je penses `elixir`, `kotlin`, `swift`, `dart` et `zig` par exemple
