### ISSUE TITLE
Générer un partenaire quotidien

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#259]
## Design

Chaque jour, on associe aléatoirement les participants par pair de _buddies_
Le partenaire du jour sera affiché juste au-dessus du calendrier
![Screenshot 2023-10-22 at 11 13 22](https://github.com/pil0u/lewagon-aoc/assets/8350914/6b167510-0fc4-47ce-89ef-ff90f884a4cb)

Contrainte : ne pas créer 2 fois les mêmes paires.

## Logique

C'est une Issue très "algo" 💡 

La complexité réside dans le fait que les participants sont en perpétuel croissance. Une façon de gérer ça serait de : 
* faire tourner l'algo à heure fixe (5:59 ?) et associer les participants existants
* si le nombre est impair, m'exclure moi du système (par simplicité)
* ne rien afficher pour les participants qui rejoignent en cours de route : ils seront dans le pool de participants le jour suivant

**Comment by Aquaj** [comment]
Y'a plus simple: ex l'algo de buddies du Wagon. C'est un [round-robin](https://en.wikipedia.org/wiki/Round-robin_tournament) avec une seed aléatoire, donc tu as de la variabilité et tu es garanti de pas faire de redites. 
Tu as de l'aléatoire pour le setup mais tout le reste est déterministe, ça obvie tout besoin de stockage.

**Comment by Aquaj** [comment]
Ah yes ! On a une taille variable 🤔 J'avais zappé ce détail, je comprends mieux !
