### ISSUE TITLE
Ajouter des tests sur le sanitizer du code sharing ?

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#260]
@Aquaj On a eu quelques soucis l'année dernière sur cet aspect, ça peut valoir le coup que tu fasses une passe rapide pour s'assurer que c'est pas trop bancal, voire ajouter des tests si besoin.

**Comment by Aquaj** [comment]
Je me souviens qu'on a eu des soucis, mais plus du tout quoi 😅 Je vais voir si je peux retrouver, ça nous fera des cas de test.

**Comment by Aquaj** [comment]
Je viens de me faire 15 pages des images partagées sur le chan #aoc et 0 exemple 😞

**Comment by Aquaj** [comment]
Déjà corrigé par #217 du coup, si je ne m'abuse.

**Comment by wJoenn** [comment]
Y a plus de sanitizer sur les snippets donc y a rien a ecrire comme test et ca fonctionne.
On peu close je penses
![image](https://github.com/pil0u/lewagon-aoc/assets/75388869/305811d3-b949-4c2a-abde-211d07a79e68)
