### ISSUE TITLE
Ajuster la logique de déblocage des solutions

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#262]
Aujourd'hui, il n'est possible d'accéder aux solutions uniquement si on a résolu le puzzle (`SolvedPuzzleConstraint`) :
* c'est frustrant pour les participants qui veulent apprendre
* ça crée une incentive à résoudre avec un code tombé du camion pour y accéder

Solution : 
* garder cette contrainte pendant les 24 premières heures d'un puzzle
* débloquer les solutions pour tout le monde 24 heure après la sortie d'un puzzle

**Comment by Aquaj** [comment]
> débloquer les solutions pour tout le monde 24 heure après la sortie d'un puzzle

Questionable 24 au lieu de 48 non ? Tu continues à gagner des points pendant le 24-48h, donc ça me surprend de l'ouvrir si tôt.
