### ISSUE TITLE
Afficher les 5 premières lignes des snippets par défaut

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#265]
## Problème

Pour un puzzle donné, le nombre très important de solutions les rendent un peu lisibles.

## Solution

L'idée serait de réduire l'affichage, en affichant les 5-10 premières lignes par snippet et un moyen très simple de "dévoiler" le reste ou de "rembobiner" chaque snippet.

**Comment by wJoenn** [comment]
J'vais etre honette, je deteste devoir gerer le clamping de paragraphe.

C'est hyper simple pour avoir une base en place, suffit d'utiliser `line-clamp-5` comme class Tailwind et ca va clamp après 5 lignes en ajoutant un ellipsis a la derniere ligne.

Mais y a pas moyen d'avoir une transition la dessus et pour pouvoir en avoir une (imo c'est imperatif) faut faire des trucs a coup de `max-height` et `overflow` en prenant compte la hauteur pre-clamping de l'element etc.
J'ai deja tenté plusieurs fois, j'ai jamais eu un resultat qui me convenait 😓

Du coup si qqn d'autre veut faire il est la bienvenue 😄
