### ISSUE TITLE
Permettre aux utilisateurs de voter sur les snippets en émojis

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#269]
"À la GitHub", l'idée est de permettre de voter avec un set limité d’émojis, porteurs de sens : 
* 🎓 pour une solution exemplaire, où on apprend des choses
* 🤯 pour une solution inattendue, "blows my mind"
* 👏 pour applaudir une solution, une célébration générique

S'inspirer à 100% de ce que GitHub permet de faire, mais avec ces émojis.

## Design

* Les réactions doivent être stockées en base et dans un modèle 
* Les 3 émojis possibles sont 👏, 🎓 et 🤯, affichés dans cet ordre, avec une explication en hover : 
    * 👏 Nice solution, well done
    * 🎓 Outstanding solution to help others learn
    * 🤯 Mind-blowing or unexpected solution
* Pour chaque snippet disponible, un utilisateur ne peut choisir qu'un seul émoji parmi les 3
* Les 3 émojis apparaissent systématiquement sur chaque snippet, avec leur compteur respectif -> ça évite d'avoir à cliquer sur (+) puis choisir l'émoji en question
* Les compteurs d'émoji ont 2 états : **sélectionné** par l'utilisateur ou **non sélectionné**
* On ne peut pas voter pour ses propres snippets
* (une fois le JS en place) un utilisateur peut changer l'émoji associé à un snippet quand il le souhaite : 
    * s'il clique sur l'émoji qu'il avait sélectionné auparavant, la réaction disparaît (`destroy`)
    * s'il clique sur un autre émoji que celui sélectionné, la sélection change automatiquement (`update` ?)

**Comment by Aquaj** [comment]
Les émojis remplacent le vote ou viennent juste en complément? Et s'ils remplacent le vote:
- Est-ce qu'on suit Github ou pas vàv du multi-vote (je peux réagir avec N émojis, cf ce post) ou est-ce qu'on limite à un ?
- Seule façon de +1 une solution sans donner un avis dessus c'est 👏  du coup ? (ça c'est plus moi pour confirmer ma bonne compréhension que pour challenger)
