### ISSUE TITLE
Empêcher un utilisateur de mettre à jour le referral si confirmé

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#293]

**Comment by wJoenn** [comment]
Qu'est ce que tu entend par "si confirmé" ?
Tu ne veux pas qu'un User puisse changer dans la page de setup ou tu ne veux pas qu'un user puisse changer une fois qu'il est setup ?

**Comment by wJoenn** [comment]
Bah une fois que c'es le cas il a plus accès a la page de `setup` et c'est le seul endroit qui comprend un formulaire pour modifier son referrer.

Ca veut dire qu'on ne donne aucun moyen a un user d'update ca ensuite.
Le seul moyen qui j'imagines ca serait de reverse engineer l'api et de faire un POST directement depuis un server. Tu penses que c'est qqch qui doit nous inquieter ? 😄 

Après ca demande pas grand chose de mettre une validation pour ca, izoké
