### ISSUE TITLE
Renvoyer des erreurs (flash) sur les différents formulaires

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#307]
- [x] ~~Si un utilisateur a déjà un `batch_id` non nil, renvoyer une erreur s'il essaye de le changer~~
- [x] ~~Si un utilisateur a déjà un `batch_id` non nil (et donc une ville), renvoyer une erreur s'il essaye de changer sa ville~~
- [x] Si un utilisateur essaye un `referral_code` qui n'existe pas, renvoyer une erreur
- [ ] ~~Si un utilisateur essaye de changer son `referrer_id` alors qu'il est `confirmed`, renvoyer une erreur~~

**Comment by wJoenn** [comment]
Meme commentaire que pour https://github.com/pil0u/lewagon-aoc/issues/293#issuecomment-1806858571 concernant

> Si un utilisateur essaye de changer son referrer_id alors qu'il est confirmed, renvoyer une erreur
