### ISSUE TITLE
Ajouter un dropdown dans les paramètres utilisateurs : comment ont-ils connu la plateforme

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#334]
## Design

À adosser au modèle utilisateur, ajouter un attribut `event_awareness` qui contient une énum de ces possibilités de réponses : 
* Slack channel #aoc
* Slack channel #general 
* Slack channel from my city
* Slack channel from my batch
* Email newsletter
* Launch party in Brussels
* Testing workshop in London
* LinkedIn
* Facebook
* Instagram

La question sera à mettre dans le composant de formulaire utilisateur, pour qu'on la voit dans les settings et dans le setup.

Le label à mettre devant : `How did you hear about us?`

**Comment by wJoenn** [comment]
`P1 - 16 novembre`
-> Publié le 19 Novembre 😄 

Je fais ca ajd
