### ISSUE TITLE
Erreur rspec GitHub Action

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#378]
Sur un premier run j'ai eu cette erreur : https://github.com/pil0u/lewagon-aoc/actions/runs/7052956508/job/19199092059?pr=376

Je suis curieux de savoir si ça vient de GitHub Action ou bien de nos tests

**Comment by Aquaj** [comment]
Je pense qu'on doit avoir un flaky. Je comprends pas pourquoi le log nous affiche pas la seed du run par contre, ça nous aurait permis de confirmer que c'est bien ça.

**Comment by wJoenn** [comment]
L'erreur disparait si tu re-run les test donc je ne penses pas que ca vienne de nous.

**Comment by Aquaj** [comment]
> L'erreur disparait si tu re-run les test donc je ne penses pas que ca vienne de nous.

C'est le propre d'un [flaky](https://www.datadoghq.com/knowledge-center/flaky-tests/). Ça veut pas dire que ça vienne pas de nous, si une spec est mal isolée, en fonction de l'ordre de run (que RSpec randomise à chaque fois) ça peut fail une fois et remarcher une autre.

**Comment by pil0u** [comment]
Not reproduced, to monitor in 2024.
