### ISSUE TITLE
Fix JS interval for countdown

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#632]
Ok, c'est pas une solution très comprehensive ni la good practice.
La raison pour laquelle tu avais plein de refresh c'est a cause de l'interval que tu as creer dans `connect`

Ce qu'il faudrait faire c'est
```js
connect () {
  if (new Date() < new Date(this.launchDateValue)) {
    this.interval = setInterval(() => this.#updateClock(), 23)
  }
}

disconnect () {
  clearInterval(this.interval)
}
```

_Originally posted by @wJoenn in https://github.com/pil0u/lewagon-aoc/pull/623#discussion_r1802474124_

**Comment by pil0u** [comment]
@wJoenn J'ai tenté ton approche, mais j'ai toujours le même problème. Bizarrement, je ne l'ai que sur mon Firefox Linux, et pas sur mon Firefox Mac.

**Comment by wJoenn** [comment]
Tu peux essayer ceci ?
https://github.com/pil0u/lewagon-aoc/pull/637
