### ISSUE TITLE
Bug: if the puzzle does not have a `thread_ts`, `post_slack_message` returns an error

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#650]
Likelyhood: low.

If for some reason the `thread_ts` is not set for a given puzzle, posting a solution returns an error 500 (although the solution is correctly posted).

```ruby
    if @snippet.save
      post_slack_message
...
  def post_slack_message
    client = Slack::Web::Client.new
    puzzle = Puzzle.by_date(Aoc.begin_time.change(day: params[:day]))
    username = "<#{helpers.profile_url(current_user.uid)}|#{current_user.username}>"
    solution = "<#{helpers.snippet_url(day: @snippet.day, challenge: @snippet.challenge, anchor: @snippet.id)}|solution>"
    text = "#{username} submitted a new #{solution} for part #{params[:challenge]} in :#{@snippet.language}-hd:"
    client.chat_postMessage(channel: ENV.fetch("SLACK_CHANNEL", "#aoc-dev"), text:, thread_ts: puzzle.thread_ts) # <<<<< HERE
  end
```

⚠️ If the `thread_ts` is set to `nil` (like `puzzle&.thread_ts`), then the message is posted in the channel directly 😬

**Comment by wJoenn** [comment]
Conditions pour que ca arrive
- Le scrapper n'arrive pas a recuperer le titre du jour, alors pas de puzzle du tout
- Le SDK de slack ne parvient pas a poster un message, alors le thread_ts sera `nil` et le job aure throw une error parce que `@message["message"]["ts"]` fonctionnera probablement pas (ce qui veut dire que le puzzle n'est pas saved)

Comment tu voudrais gerer ces erreurs ?

**Comment by pil0u** [comment]
Je sais pas, je sais juste que ça m'est arrivé en local pour je ne sais plus quelle raison.

En préventif, on pourrait demander au job qui génère le thread de balancer un message dans #aoc-dev systématiquement avec les infos du Puzzle qui vient d'être créé. Ça coûte pas cher et chaque matin on se rassure.

**Comment by wJoenn** [comment]
C'est deja le cas quand il n'y a pas de titre, on a un message d'erreur qui nous dit "title not found for day x"

**Comment by pil0u** [comment]
C'est uniquement dans le cas où on n'a pas réussi à scraper adventofcode.com, mais si le `@puzzle.thread_ts` est `nil` on le sait pas.

J'avais pas creusé la solution avant que tu rebondisses ici, en en parlant je pense qu'un simple
```ruby
post_message(channel: "#aoc-dev", text: "ALERTE ROUGE PUZZLE SANS THREAD") if @puzzle.thread_ts.nil?
```
ça suffirait

**Comment by pil0u** [comment]
Je suis d'accord que normalement c'est corrélé. Et au pire du pire, y a un message qui pop dans #aoc 😂
