### ISSUE TITLE
Calendar | Ajouter un indicateur de difficulté des puzzles

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#81]
Simplest approach is by leveraging timestamps from the top 100 of the past years and determine absolute threshold as an output:
- :green_circle: very easy (< 2 minutes)
- :yellow_circle: easy (between 2 and 10 minutes)
- :orange_circle: hard (between 10 and 20 minutes)
- :red_circle: very hard (> 20 minutes)

**Comment by Aquaj** [comment]
Hyper cool. Potentiellement à intégrer en mode expérimental.

**Comment by pil0u** [comment]
* Create a job that call Jules' API daily (after 5 minutes, 10 minutes, 30 minutes, 1 hour and 2 hours)
* Create a `difficulty` field for the `Puzzle` model and update it with the new value every call
* Display an emoji next to the puzzle link on the day page. 1 emoji for each part (🟢 🟡 🟠 🔴 ⚪)
